.386
DATA SEGMENT USE16
    INPUT DB 'PLEASE INPUT A NUM(0~9):$'
    ERROR DB 'ERROR INPUT$'
    TAB   DB '  1$','  8$',' 27$',' 64$','125$','343$','512$','512$','729$'
DATA ENDS

STACK SEGMENT USE16
          DB 200 DUP(0)
STACK ENDS


CODE SEGMENT USE16
          ASSUME DS:DATA,CS:CODE,SS:STACK

    BEGIN:MOV    AX,DATA
          MOV    CS,AX

CODE ENDS
    END BEGIN